bin_numeric_features: null
categorical_features: null
categorical_imputation: constant
cluster_iter: 20
combine_rare_levels: false
create_clusters: false
date_features: null
feature_interaction: false
feature_ratio: false
feature_selection: false
feature_selection_threshold: 0.8
group_features: null
group_names: null
handle_unknown_categorical: true
high_cardinality_features: null
high_cardinality_method: frequency
ignore_features: null
ignore_low_variance: false
interaction_threshold: 0.01
multicollinearity_threshold: 0.9
normalize: false
normalize_method: zscore
numeric_features: null
numeric_imputation: mean
ordinal_features: null
outliers_threshold: 0.05
pca: false
pca_components: null
pca_method: linear
polynomial_degree: 2
polynomial_features: false
polynomial_threshold: 0.1
profile: false
rare_level_threshold: 0.1
remove_multicollinearity: false
remove_outliers: false
sample_estimator: null
sampling: true
session_id: null
silent: false
train_size: 0.7
transform_target: false
transformation: false
transformation_method: yeo-johnson
trigonometry_features: false
unknown_categorical_method: least_frequent
