Kfolds: 10
analysis_name: my-regression
auto_select_best_model_by: R2
auto_tune: true
bin_numeric_features: false
categorical_features: None
categorical_imputation: constant
cluster_iter: '20'
combine_rare_levels: false
create_clusters: false
custom_setup: true
date_features: None
demo_dataset: boston
demo_run: true
feature_interaction: false
feature_ratio: false
feature_selection: false
feature_selection_threshold: '0.8'
group_features: None
group_names: None
handle_unknown_categorical: false
high_cardinality_features: None
high_cardinality_method: frequency
ignore_features: None
ignore_low_variance: false
interaction_threshold: '0.01'
multicollinearity_threshold: '0.9'
normalize: false
normalize_method: zscore
numeric_features: None
numeric_imputation: mean
ordinal_features: None
outliers_threshold: '0.05'
pca: false
pca_components: '0.99'
pca_method: linear
polynomial_degree: '2'
polynomial_features: false
polynomial_threshold: '0.1'
profile: true
rare_level_threshold: false
remove_multicollinearity: false
remove_outliers: false
sample_estimator: None
sampling: true
session_id: None
silent: true
train_size: '0.7'
transform_target: false
transform_target_method: box-tox
transformation: false
transformation_method: yeo-johnson
trigonometry_features: false
unknown_categorical_method: least_frequent
user_name: lmn
user_selected_model: Auto select best model
view_config: false
